(module
  (memory (export "mem") 2048)
  ;; ---- NN: C[M,N] = A[M,K] @ B[K,N]  (清零后累加) ----
  (func (export "nn")
    (param $a i32) (param $b i32) (param $c i32) (param $M i32) (param $N i32) (param $K i32)
    (local $i i32) (local $k i32) (local $j i32) (local $n4 i32)
    (local $c0 i32) (local $c1 i32) (local $c2 i32) (local $c3 i32) (local $ai i32) (local $bk i32)
    (local $v0 v128) (local $v1 v128) (local $v2 v128) (local $v3 v128) (local $bv v128)
    (local $t i32) (local $rows i32)
    (local.set $j (i32.const 0))
    (block $zd (loop $z
      (br_if $zd (i32.ge_u (local.get $j) (i32.mul (i32.mul (local.get $M) (local.get $N)) (i32.const 4))))
      (f32.store (i32.add (local.get $c) (local.get $j)) (f32.const 0))
      (local.set $j (i32.add (local.get $j) (i32.const 4))) (br $z)))
    (local.set $n4 (i32.and (local.get $N) (i32.const 0xfffffffc)))
    (local.set $i (i32.const 0))
    (block $id (loop $il
      (br_if $id (i32.ge_u (local.get $i) (local.get $M)))
      (local.set $rows (i32.sub (local.get $M) (local.get $i)))
      (if (i32.gt_u (local.get $rows) (i32.const 4)) (then (local.set $rows (i32.const 4))))
      (local.set $c0 (i32.add (local.get $c) (i32.mul (i32.mul (local.get $i) (local.get $N)) (i32.const 4))))
      (local.set $ai (i32.add (local.get $a) (i32.mul (i32.mul (local.get $i) (local.get $K)) (i32.const 4))))
      (local.set $t (i32.mul (local.get $N) (i32.const 4)))
      (local.set $c1 (i32.add (local.get $c0) (local.get $t)))
      (local.set $c2 (i32.add (local.get $c1) (local.get $t)))
      (local.set $c3 (i32.add (local.get $c2) (local.get $t)))
      (local.set $k (i32.const 0))
      (block $kd (loop $kl
        (br_if $kd (i32.ge_u (local.get $k) (local.get $K)))
        (local.set $v0 (f32x4.splat (f32.load (i32.add (local.get $ai) (i32.mul (local.get $k) (i32.const 4))))))
        (local.set $v1 (f32x4.splat (f32.const 0))) (local.set $v2 (f32x4.splat (f32.const 0))) (local.set $v3 (f32x4.splat (f32.const 0)))
        (if (i32.gt_u (local.get $rows) (i32.const 1)) (then (local.set $v1 (f32x4.splat (f32.load (i32.add (local.get $ai) (i32.mul (i32.add (local.get $k) (local.get $K)) (i32.const 4))))))))
        (if (i32.gt_u (local.get $rows) (i32.const 2)) (then (local.set $v2 (f32x4.splat (f32.load (i32.add (local.get $ai) (i32.mul (i32.add (local.get $k) (i32.mul (local.get $K) (i32.const 2))) (i32.const 4))))))))
        (if (i32.gt_u (local.get $rows) (i32.const 3)) (then (local.set $v3 (f32x4.splat (f32.load (i32.add (local.get $ai) (i32.mul (i32.add (local.get $k) (i32.mul (local.get $K) (i32.const 3))) (i32.const 4))))))))
        (local.set $bk (i32.add (local.get $b) (i32.mul (i32.mul (local.get $k) (local.get $N)) (i32.const 4))))
        (local.set $j (i32.const 0))
        (block $jd (loop $jl
          (br_if $jd (i32.ge_u (local.get $j) (local.get $n4)))
          (local.set $t (i32.mul (local.get $j) (i32.const 4)))
          (local.set $bv (v128.load (i32.add (local.get $bk) (local.get $t))))
          (v128.store (i32.add (local.get $c0) (local.get $t)) (f32x4.add (v128.load (i32.add (local.get $c0) (local.get $t))) (f32x4.mul (local.get $v0) (local.get $bv))))
          (if (i32.gt_u (local.get $rows) (i32.const 1)) (then (v128.store (i32.add (local.get $c1) (local.get $t)) (f32x4.add (v128.load (i32.add (local.get $c1) (local.get $t))) (f32x4.mul (local.get $v1) (local.get $bv))))))
          (if (i32.gt_u (local.get $rows) (i32.const 2)) (then (v128.store (i32.add (local.get $c2) (local.get $t)) (f32x4.add (v128.load (i32.add (local.get $c2) (local.get $t))) (f32x4.mul (local.get $v2) (local.get $bv))))))
          (if (i32.gt_u (local.get $rows) (i32.const 3)) (then (v128.store (i32.add (local.get $c3) (local.get $t)) (f32x4.add (v128.load (i32.add (local.get $c3) (local.get $t))) (f32x4.mul (local.get $v3) (local.get $bv))))))
          (local.set $j (i32.add (local.get $j) (i32.const 4))) (br $jl)))
        ;; N 的尾数
        (block $td (loop $tl
          (br_if $td (i32.ge_u (local.get $j) (local.get $N)))
          (local.set $t (i32.mul (local.get $j) (i32.const 4)))
          (f32.store (i32.add (local.get $c0) (local.get $t)) (f32.add (f32.load (i32.add (local.get $c0) (local.get $t))) (f32.mul (f32x4.extract_lane 0 (local.get $v0)) (f32.load (i32.add (local.get $bk) (local.get $t))))))
          (if (i32.gt_u (local.get $rows) (i32.const 1)) (then (f32.store (i32.add (local.get $c1) (local.get $t)) (f32.add (f32.load (i32.add (local.get $c1) (local.get $t))) (f32.mul (f32x4.extract_lane 0 (local.get $v1)) (f32.load (i32.add (local.get $bk) (local.get $t))))))))
          (if (i32.gt_u (local.get $rows) (i32.const 2)) (then (f32.store (i32.add (local.get $c2) (local.get $t)) (f32.add (f32.load (i32.add (local.get $c2) (local.get $t))) (f32.mul (f32x4.extract_lane 0 (local.get $v2)) (f32.load (i32.add (local.get $bk) (local.get $t))))))))
          (if (i32.gt_u (local.get $rows) (i32.const 3)) (then (f32.store (i32.add (local.get $c3) (local.get $t)) (f32.add (f32.load (i32.add (local.get $c3) (local.get $t))) (f32.mul (f32x4.extract_lane 0 (local.get $v3)) (f32.load (i32.add (local.get $bk) (local.get $t))))))))
          (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $tl)))
        (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $kl)))
      (local.set $i (i32.add (local.get $i) (i32.const 4))) (br $il)))
  )
  ;; ---- TNacc: C[K,N] += A[M,K]^T @ B[M,N] ----
  (func (export "tnacc")
    (param $a i32) (param $b i32) (param $c i32) (param $M i32) (param $N i32) (param $K i32)
    (local $m i32) (local $k i32) (local $j i32) (local $n4 i32)
    (local $am i32) (local $bm i32) (local $ck i32) (local $t i32)
    (local $av v128) (local $bv v128) (local $s f32)
    (local.set $n4 (i32.and (local.get $N) (i32.const 0xfffffffc)))
    (local.set $m (i32.const 0))
    (block $md (loop $ml
      (br_if $md (i32.ge_u (local.get $m) (local.get $M)))
      (local.set $am (i32.add (local.get $a) (i32.mul (i32.mul (local.get $m) (local.get $K)) (i32.const 4))))
      (local.set $bm (i32.add (local.get $b) (i32.mul (i32.mul (local.get $m) (local.get $N)) (i32.const 4))))
      (local.set $k (i32.const 0))
      (block $kd (loop $kl
        (br_if $kd (i32.ge_u (local.get $k) (local.get $K)))
        (local.set $s (f32.load (i32.add (local.get $am) (i32.mul (local.get $k) (i32.const 4)))))
        (if (f32.ne (local.get $s) (f32.const 0)) (then
          (local.set $av (f32x4.splat (local.get $s)))
          (local.set $ck (i32.add (local.get $c) (i32.mul (i32.mul (local.get $k) (local.get $N)) (i32.const 4))))
          (local.set $j (i32.const 0))
          (block $jd (loop $jl
            (br_if $jd (i32.ge_u (local.get $j) (local.get $n4)))
            (local.set $t (i32.mul (local.get $j) (i32.const 4)))
            (v128.store (i32.add (local.get $ck) (local.get $t))
              (f32x4.add (v128.load (i32.add (local.get $ck) (local.get $t)))
                         (f32x4.mul (local.get $av) (v128.load (i32.add (local.get $bm) (local.get $t))))))
            (local.set $j (i32.add (local.get $j) (i32.const 4))) (br $jl)))
          (block $td (loop $tl
            (br_if $td (i32.ge_u (local.get $j) (local.get $N)))
            (local.set $t (i32.mul (local.get $j) (i32.const 4)))
            (f32.store (i32.add (local.get $ck) (local.get $t))
              (f32.add (f32.load (i32.add (local.get $ck) (local.get $t)))
                       (f32.mul (local.get $s) (f32.load (i32.add (local.get $bm) (local.get $t))))))
            (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $tl)))
        ))
        (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $kl)))
      (local.set $m (i32.add (local.get $m) (i32.const 1))) (br $ml)))
  )
  ;; ---- NT: C[M,K] = A[M,N] @ B[K,N]^T  （沿 N 做点积） ----
  (func (export "nt")
    (param $a i32) (param $b i32) (param $c i32) (param $M i32) (param $K i32) (param $N i32)
    (local $m i32) (local $k i32) (local $j i32) (local $n4 i32)
    (local $am i32) (local $bk i32) (local $cm i32) (local $t i32)
    (local $acc v128) (local $s f32)
    (local.set $n4 (i32.and (local.get $N) (i32.const 0xfffffffc)))
    (local.set $m (i32.const 0))
    (block $md (loop $ml
      (br_if $md (i32.ge_u (local.get $m) (local.get $M)))
      (local.set $am (i32.add (local.get $a) (i32.mul (i32.mul (local.get $m) (local.get $N)) (i32.const 4))))
      (local.set $cm (i32.add (local.get $c) (i32.mul (i32.mul (local.get $m) (local.get $K)) (i32.const 4))))
      (local.set $k (i32.const 0))
      (block $kd (loop $kl
        (br_if $kd (i32.ge_u (local.get $k) (local.get $K)))
        (local.set $bk (i32.add (local.get $b) (i32.mul (i32.mul (local.get $k) (local.get $N)) (i32.const 4))))
        (local.set $acc (f32x4.splat (f32.const 0)))
        (local.set $j (i32.const 0))
        (block $jd (loop $jl
          (br_if $jd (i32.ge_u (local.get $j) (local.get $n4)))
          (local.set $t (i32.mul (local.get $j) (i32.const 4)))
          (local.set $acc (f32x4.add (local.get $acc)
            (f32x4.mul (v128.load (i32.add (local.get $am) (local.get $t)))
                       (v128.load (i32.add (local.get $bk) (local.get $t))))))
          (local.set $j (i32.add (local.get $j) (i32.const 4))) (br $jl)))
        (local.set $s (f32.add (f32.add (f32x4.extract_lane 0 (local.get $acc)) (f32x4.extract_lane 1 (local.get $acc)))
                               (f32.add (f32x4.extract_lane 2 (local.get $acc)) (f32x4.extract_lane 3 (local.get $acc)))))
        (block $td (loop $tl
          (br_if $td (i32.ge_u (local.get $j) (local.get $N)))
          (local.set $t (i32.mul (local.get $j) (i32.const 4)))
          (local.set $s (f32.add (local.get $s) (f32.mul (f32.load (i32.add (local.get $am) (local.get $t))) (f32.load (i32.add (local.get $bk) (local.get $t))))))
          (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $tl)))
        (f32.store (i32.add (local.get $cm) (i32.mul (local.get $k) (i32.const 4))) (local.get $s))
        (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $kl)))
      (local.set $m (i32.add (local.get $m) (i32.const 1))) (br $ml)))
  )
)
